### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by CreditTone** [CreditTone/hooker#11]
stephen@ubuntu:~/hooker/com.yaotong.crackme$ ./objection 

A newer version of objection is available!
You have v1.10.1 and v1.10.2 is ready for download.

Upgrade with: pip3 install objection --upgrade
For more information, please see: https://github.com/sensepost/objection/wiki/Updating

Traceback (most recent call last):
  File "/home/stephen/.pyenv/versions/3.9.0/bin/objection", line 33, in <module>
    sys.exit(load_entry_point('objection==1.10.1', 'console_scripts', 'objection')())
  File "/home/stephen/.pyenv/versions/3.9.0/bin/objection", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/site-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/site-packages/objection/console/repl.py", line 15, in <module>
    from .commands import COMMANDS
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/site-packages/objection/console/commands.py", line 10, in <module>
    from ..commands import sqlite
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/site-packages/objection/commands/sqlite.py", line 7, in <module>
    from litecli.main import LiteCli
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/site-packages/litecli/main.py", line 13, in <module>
    from sqlite3 import OperationalError
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/stephen/.pyenv/versions/3.9.0/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
stephen@ubuntu:~/hooker/com.yaotong.crackme$

**Comment by CreditTone** [comment]
pyenv安装的时候，没有安装_sqlite3导致的。暂时想到重装python3，没有其他办法。https://stackoverflow.com/questions/43993890/modulenotfounderror-no-module-named-sqlite3/48229955
