### ISSUE TITLE
hook onClick绑定事件问题

### ISSUE THREAD

**Issue by zjcnew** [CreditTone/hooker#23]
通过click.js hook到被点击View的真实VClass是android.support.v7.widget.AppCompatTextView，这个系统类，以及堆栈里都是系统类，对分析毫无帮助啊，我该怎么办？
ViewClz: android.support.v7.widget.AppCompatTextView
ViewId: 2131296475
------------startFlag:6fq79b4f,objectHash:obj:873346533,thread(id:1,name:main),timestamp:1619427614290---------------
public boolean android.view.View.performClick()
        at android.view.View.performClick(Native Method)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
------------endFlag:6fq79b4f,usedtime:8---------------

**Comment by CreditTone** [comment]
命令行输入：v ｛viewid｝探测下

**Comment by CreditTone** [comment]
搞定没

**Comment by zjcnew** [comment]
可以，有点信息。
