### ISSUE TITLE
frida.InvalidOperationError: script has been destroyed

### ISSUE THREAD

**Issue by uceka** [CreditTone/hooker#48]
Hi,

Could you check the following error. 

```
➜  hooker git:(master) ./hooker
 PID  Name                  Identifier
----  --------------------  --------------------------------
3370  Chrome                com.android.chrome
1594  Google Play Store     com.android.vending
4325  Messaging             com.android.messaging
1307  Phone                 com.android.dialer
   -  Amaze                 com.amaze.filemanager
   -  Calendar              com.android.calendar
   -  Camera                com.android.camera2
   -  Clock                 com.android.deskclock
   -  Contacts              com.android.contacts
   -  Custom Locale         com.android.customlocale2
   -  Development Settings  com.android.development_settings
   -  Email                 com.android.email
   -  Files                 com.android.documentsui
   -  Gallery               com.android.gallery3d
   -  Search                com.android.quicksearchbox
   -  Settings              com.android.settings
   -  Superuser             com.genymotion.superuser
   -  WebView Shell         org.chromium.webview_shell
   -  drozer Agent          com.mwr.dz
Enter the need to attach package.
: sg.ndi.sp
It's sg.ndi.sp that you have attached app.
Traceback (most recent call last):
  File "/Users/test/hooker/hooker.py", line 100, in attach
    createHookingEnverment(packageName, online_script.exports.mainactivity())
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 468, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 400, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script has been destroyed

--------------------------------------------------
Please enter e, s, j, c or ex command.
a: Discovering activities.
b: Discovering services.
c: Discovering object. eg:'c {objectId}'
d: Object2Explain. eg:'d {objectId}'
v: Discovering view. eg:'v {viewId}'
e: Determines whether a class exists. eg:'e android.app.Application'
s: Discovering classes by a class'regex. eg:'s com.tencent.mm.Message.*'
t: Discovering offspring classes by a class'name. eg:'t com.tencent.mm.BasicActivity'
j: Generating hooked js. eg:'j okhttp3.Request$Builder:build'
k: Generating hooked the string generation js with a keyword. eg:'k {YourKeyword}'
l: Generating hooked the param generation js with a param keyword. eg:'l {YourKeyword}'
m: Discovering so module.
ex: Exit to the upper layer. eg:'ex'
```

**Comment by oooodogecoin** [comment]
Is this app running？

**Comment by uceka** [comment]
Nope, it's not opening

**Comment by oooodogecoin** [comment]
The first is to open this app，then to use hooker attach the process

**Comment by uceka** [comment]
Yes, I already opened the app but didn't work. I can share the apk with you, if you wish ?

**Comment by CreditTone** [comment]
Give me your app

> Yes, I already opened the app but didn't work. I can share the apk with you, if you wish ?

Give me your app

**Comment by uceka** [comment]
> Give me your app
> 
> > Yes, I already opened the app but didn't work. I can share the apk with you, if you wish ?
> 
> Give me your app

Just sent via email.
Thanks

**Comment by CreditTone** [comment]
The app has a de-debugging mechanism that hooker does not yet support.  You can learn more about https://frida.re/docs/gadget/
