### ISSUE TITLE
ModuleNotFoundError: No module named 'frida'

### ISSUE THREAD

**Issue by Liuxw17** [CreditTone/hooker#54]
```
➜  hooker git:(2022074_first_use) ✗ ./hooker
./hooker: line 6: frida-ps: command not found
Enter the need to attach package.
:
It's  that you have attached app.
Traceback (most recent call last):
  File "/Users/xxx/Desktop/hooker/hooker.py", line 6, in <module>
    import frida, sys
ModuleNotFoundError: No module named 'frida'
```
![image](https://user-images.githubusercontent.com/32437197/177077263-d4115b6c-97a0-4eb5-982a-303af7a12b45.png)

已经安装了frida和frida-tools，为什么运行`.hooker`会提示如下报错？

**Comment by ff-frida** [comment]
> ```
> ➜  hooker git:(2022074_first_use) ✗ ./hooker
> ./hooker: line 6: frida-ps: command not found
> Enter the need to attach package.
> :
> It's  that you have attached app.
> Traceback (most recent call last):
>   File "/Users/xxx/Desktop/hooker/hooker.py", line 6, in <module>
>     import frida, sys
> ModuleNotFoundError: No module named 'frida'
> ```
> 
> ![image](https://user-images.githubusercontent.com/32437197/177077263-d4115b6c-97a0-4eb5-982a-303af7a12b45.png)
> 
> 已经安装了frida和frida-tools，为什么运行`.hooker`会提示如下报错？

我也遇到这个问题，你是怎么解决的，对py的环境有什么要求吗
