### ISSUE TITLE
Unable to attach using identifier

### ISSUE THREAD

**Issue by gaplan** [CreditTone/hooker#55]
![Screen Shot 2022-07-13 at 07 24 09](https://user-images.githubusercontent.com/2036941/178650365-3d5427fe-2a9d-48fc-92b7-2bd26c39ce22.png)

  PID  Name                          Identifier                                   
-----  ----------------------------  ---------------------------------------------
 7313  AirDroid                      com.sand.airdroid                            
 8263  Calendar                      com.samsung.android.calendar                 
 7572  Contacts                      com.samsung.android.contacts                 
 7572  Contacts                      com.samsung.android.contacts                 
26770  Dergilik                      com.arneca.dergilik.main3x                   
 5384  Google                        com.google.android.googlequicksearchbox      
 5384  Google                        com.google.android.googlequicksearchbox      
 6258  Google Play Store             com.android.vending                          
26635  Instagram Lite                com.instagram.lite                           
 6180  Lite                          com.facebook.lite                            
 6831  Magisk                        com.topjohnwu.magisk                         
26939  Official TWRP App             me.twrp.twrpapp                              
25921  S Voice                       com.samsung.voiceserviceplatform             
26081  Samsung Music                 com.sec.android.app.music                    
19360  TikTok                        com.zhiliaoapp.musically                     
27067  TikTok Lite                   com.zhiliaoapp.musically.go                  
 3608  抖音                            com.ss.android.ugc.aweme                     
Enter the need to attach package.
:    com.ss.android.ugc.aweme
It's com.ss.android.ugc.aweme that you have attached app.
Traceback (most recent call last):
  File "/Users/selcukakbulut/temp/andro/hooker/hooker.py", line 93, in attach
    online_session = rdev.attach(target)
  File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 165, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
  File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 193, in _pid_of
    return self.get_process(target).pid
  File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 121, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'com.ss.android.ugc.aweme'

--------------------------------------------------

**Comment by CreditTone** [comment]
Is the app process running?

**Comment by gaplan** [comment]
Nope.

**Comment by Oldman19** [comment]
> ![屏幕截图 2022-07-13 在 07 24 09](https://user-images.githubusercontent.com/2036941/178650365-3d5427fe-2a9d-48fc-92b7-2bd26c39ce22.png)
> 
> ```
>   PID  Name                          Identifier                                   
> -----  ----------------------------  ---------------------------------------------
>  7313  AirDroid                      com.sand.airdroid                            
>  8263  Calendar                      com.samsung.android.calendar                 
>  7572  Contacts                      com.samsung.android.contacts                 
>  7572  Contacts                      com.samsung.android.contacts                 
> 26770  Dergilik                      com.arneca.dergilik.main3x                   
>  5384  Google                        com.google.android.googlequicksearchbox      
>  5384  Google                        com.google.android.googlequicksearchbox      
>  6258  Google Play Store             com.android.vending                          
> 26635  Instagram Lite                com.instagram.lite                           
>  6180  Lite                          com.facebook.lite                            
>  6831  Magisk                        com.topjohnwu.magisk                         
> 26939  Official TWRP App             me.twrp.twrpapp                              
> 25921  S Voice                       com.samsung.voiceserviceplatform             
> 26081  Samsung Music                 com.sec.android.app.music                    
> 19360  TikTok                        com.zhiliaoapp.musically                     
> 27067  TikTok Lite                   com.zhiliaoapp.musically.go                  
>  3608  抖音                            com.ss.android.ugc.aweme                     
> Enter the need to attach package.
> :    com.ss.android.ugc.aweme
> It's com.ss.android.ugc.aweme that you have attached app.
> Traceback (most recent call last):
>   File "/Users/selcukakbulut/temp/andro/hooker/hooker.py", line 93, in attach
>     online_session = rdev.attach(target)
>   File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
>     return f(*args, **kwargs)
>   File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 165, in attach
>     return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
>   File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 193, in _pid_of
>     return self.get_process(target).pid
>   File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
>     return f(*args, **kwargs)
>   File "/opt/homebrew/lib/python3.9/site-packages/frida/core.py", line 121, in get_process
>     raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
> frida.ProcessNotFoundError: unable to find process with name 'com.ss.android.ugc.aweme'
> 
> --------------------------------------------------
> ```

Did you solve this problem, I also encountered the same error
