### ISSUE TITLE
attack无法正常运行

### ISSUE THREAD

**Issue by Oldman19** [CreditTone/hooker#61]
运行hooker后，输入包名，返回以下报错
Traceback (most recent call last):
  File "/home/kali/hooker/hooker.py", line 93, in attach                                                   
    online_session = rdev.attach(target)                                                                   
  File "/usr/local/lib/python3.10/dist-packages/frida/core.py", line 26, in wrapper                        
    return f(*args, **kwargs)                                                                              
  File "/usr/local/lib/python3.10/dist-packages/frida/core.py", line 165, in attach                        
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))                               
  File "/usr/local/lib/python3.10/dist-packages/frida/core.py", line 193, in _pid_of                       
    return self.get_process(target).pid                                                                    
  File "/usr/local/lib/python3.10/dist-packages/frida/core.py", line 26, in wrapper                        
    return f(*args, **kwargs)                                                                              
  File "/usr/local/lib/python3.10/dist-packages/frida/core.py", line 121, in get_process                   
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)              
frida.ProcessNotFoundError: unable to find process with name '这里是输入的包名，大小app都尝试过，都是这个报错'

**Comment by yetnelson** [comment]
同样问题
