### ISSUE TITLE
hook多个重名进程出错rida.ProcessNotFoundError: ambiguous name

### ISSUE THREAD

**Issue by akwolf** [CreditTone/hooker#9]
作者你好
步骤：
在使用hook工具时，
1、首先输入报名com.mediatek.ppl
2、再输入a扫描activity时提示找到两个相同的进程，

问题：
frida官方说是指定进程号来处理，当前hooker框架好像没有指定进程号的方式来处理
如果这种有两个相同进程名的应用要怎么处理？

错误日志如下：

ex: Exit to the upper layer. eg:'ex'
: a
Traceback (most recent call last):
  File "/Users/tato/hook/git/hooker/hooker.py", line 60, in attach
    online_session = rdev.attach(packageName)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 180, in _pid_of
    return self.get_process(target).pid
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 110, in get_process
    raise _frida.ProcessNotFoundError("ambiguous name; it matches: %s" % ", ".join(["%s (pid: %d)" % (process.name, process.pid) for process in matching]))
frida.ProcessNotFoundError: ambiguous name; it matches: com.mediatek.ppl (pid: 13221), com.mediatek.ppl (pid: 14430)

**Comment by CreditTone** [comment]
这是你重启了app然后马上attach。这时候手机被杀那个进程的pid还在进程列表当中，等过几秒手机既然会把无效的pid清除。——但是在这个无效的pid没有被系统清理之前，新启动了进程，这片刻（大概5~30秒）就会存在两个一模一样的进程名但是pid不一样。 

hooker是基于frida去做attach的，你给他一个进程名，但是它发现有两个一模一样的进程名它就懵逼了，然后就报这个错误！这不关hooker的事，即便你用原生frida命令也是会报这个错误的。

解决方案：
1、等几秒就好了
2、去安卓社区提交bug
3：去手机厂商提交bug

**Comment by CreditTone** [comment]
进程号attach，后期有时间会添加

**Comment by akwolf** [comment]
好的，感谢
